# Generated by Django 3.0.7 on 2020-06-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.CharField(max_length=10),
        ),
    ]
